export 'abstraction/info_data.dart';
export 'enums/gs_achievement_type.dart';
export 'enums/gs_artifact_piece.dart';
export 'enums/gs_attribute_stat.dart';
export 'enums/gs_banner.dart';
export 'enums/gs_element.dart';
export 'enums/gs_item.dart';
export 'enums/gs_item_source.dart';
export 'enums/gs_material_group.dart';
export 'enums/gs_namecard_type.dart';
export 'enums/gs_recipe_buff.dart';
export 'enums/gs_recipe_type.dart';
export 'enums/gs_region.dart';
export 'enums/gs_set_category.dart';
export 'enums/gs_weapon.dart';
export 'gs_database.json.dart' show JsonData;
export 'models/info_achievement.dart';
export 'models/info_achievement_group.dart';
export 'models/info_artifact.dart';
export 'models/info_banner.dart';
export 'models/info_character.dart';
export 'models/info_character_info.dart';
export 'models/info_character_outfit.dart';
export 'models/info_city.dart';
export 'models/info_details.dart';
export 'models/info_ingredient.dart';
export 'models/info_material.dart';
export 'models/info_namecard.dart';
export 'models/info_recipe.dart';
export 'models/info_remarkable_chest.dart';
export 'models/info_serenitea_set.dart';
export 'models/info_spincrystal.dart';
export 'models/info_version.dart';
export 'models/info_weapon.dart';
export 'models/info_weapon_info.dart';
export 'models/save_achievement.dart';
export 'models/save_character.dart';
export 'models/save_config.dart';
export 'models/save_material.dart';
export 'models/save_player_info.dart';
export 'models/save_recipe.dart';
export 'models/save_remarkable_chest.dart';
export 'models/save_reputation.dart';
export 'models/save_serenitea_set.dart';
export 'models/save_spincrystal.dart';
export 'models/save_wish.dart';

class GsDomain {
  GsDomain._();

  static const cityXpPerWeek = 420;
  static const primogemsPerWish = 160;
  static const primogemsPerCharSet = 20;
}
